os:
  - Visual Studio 2015
  
platform: x64
  - x64
  
branches:
  only:
    - master
    
install:
  - git submodule update --init --recursive
  - set PATH=C:\Program Files\CMake\bin;%PATH%

build:
  verbosity: detailed

configuration:
  - Debug
  
environment:
  matrix:
    - env_arch: "x64"
    - env_arch: "x86"
    
before_build:
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
      cmake .. -A x64 )
  - if [%env_arch%]==[x86] (
      cmake .. )
  - mkdir %APPVEYOR_REPO_COMMIT% 
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=%APPVEYOR_BUILD_FOLDER%/%APPVEYOR_REPO_COMMIT% ..
  
build_script:
  - cmake --build . --config %CONFIGURATION% --target install
  
on_success:
  - ls -R %APPVEYOR_BUILD_FOLDER%/%APPVEYOR_REPO_COMMIT%
